apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ../../base
  - secrets-env-secret.yaml
configMapGenerator:
  - name: cloud-evidence-config
    behavior: create
    literals:
      - cloud-provider=gcp
      - gcp-project-ids=ctrl-plane-prod-b1b92df2,app-plane-prod-b1b92df2
generatorOptions:
  disableNameSuffixHash: true
patches:
  - path: wi-patch.yaml
