---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloud-evidence-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: AgAhOjoS7tPugy7p5LqKNBtcU3qnVcUxagIMQyqQ3j2AMCfO5TSdXTiChmbwXKDzZ4ihBidkMzoR73JtW5Y4ahOfA/8Im0qMA9bw/ixO5tjfW5EcdlT7Wp54PUBn15jQVG3GkLgNHAI3yyV5bq0rhAf2IhF/s+xiQ3OKBFrOfLHaymSI9nt5HVr43N7genGlp66SmJNcWukP9IIxeSipJm64t6zHbVxYuXRm6qdyS+QkRBWHGBq0d8eriDSkayeZQCgWCHhZkCndQaoAVSmuGYopJEzkrozhQ1ZMTBWh126QINhMj+zd2m5Euj8bj6McuFE5MLeEHoE+8m+ZPW1T3f54POOg+ZRaDZd9EkAQdpY5Sxvam7NFuYR88XAbsErm/B3vlF3H1GbifjUF16OE293ma6+1lOHL+LIZpdDNV5Yql7Q5mRvX+VFcWKC4fg+Sudn4NpfX+qe1KNIq4ca4Nb27TjeClXakhwMiQdHwWoe2DgEbZ1Qq7HaoypBzdTg0XhfYODkpKF4eEfW1QLzx1+uRN7yMQ4fMZr5k8GmN7UQMTxLzmq20UUHA+gP+R0298nGtxh9/RiC2FaKoMMUmjPv8IKsAaUyTniFjP8DeT38DCoH4/jrYZNbcL2a61FD5eKzfER5pbI5kUhf0uOUjBqG2pgfDD8tuDQEbqVleXR8gZCdTlbeHYiWNXITJ2DZEI5269kXvYjLWH00v25Ci2j1Q0xlur+zri1eVx0/RVA==
  template:
    metadata:
      name: cloud-evidence-infra
      namespace: security

