---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloud-evidence-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: AgBdkdd+xuwfYuFO91xKeow1ZtqzCIBf6gCFW8qq/9gcOexqenxsWtDk2ZSs79rgnBPIqffHEyu2sWBJ8zs+5mNMpPUyQ5fYpP6iw7ACCepGKgUFQGqrm8ZA2beWthUOh/0yyF/gZGfX7yEK/opeuxnfoWbcjfggcoQ+I63+SR1Vy/sWBFzfi6CJmzJJ8V4nSzsBxw+EqlUeGJAXsHgxRC/vA0LoHRDR8K9ea76X/Nvo9JhbVqpZbNs9a0d6WzncmCM2wziIMWC6Byk3IC3KbqR/bzFLn6x/Fy1yxFndhsSoYl/Zen6h0L7RTfuHlz/YiwDxcgjQRR947dyKtS7VO/JdbJ4n+7StkdgQk/1n9gYedBR3BIO6reMP+yulwRKvNjOCFvnV9tRqYmyNl73fuJRKqZ7YSI9wTbQ2OwNAjX05rfaYF0HzX8nNHaHTk1ipPQD/kdW57KVZ597PYQxaoWYCj1g0WJrkA8JxQ6119RGXJNxmxBDnkWqFVhcfUnYasO60E8FgjpmOhAmeIk0pjA6edCYy3qF4Bxtzt6KbTHA5rj10EhdSSGPl8T8aCpAASK/uCCa3XTOOlO8Ywyfo9XQJzV8PuBHHZMspBydnbZWDf23Ty4/U9Ket8d9/hT1G3R14nuzZAoLa7OF0joeLadhvMyzq6TrctLem6AKHlexnlO8/EaYJAK9+0Z/D57g664SZgu/KYizVTaTF97voW+i0jymEoiSaK3HjMshwMg==
  template:
    metadata:
      name: cloud-evidence-infra
      namespace: security

