---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kubescape-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: AgBaSgXPYRRF2qfGczkcel26i2nOzlUMmelXl58AHSusxwiDcMHXt5wSIFuxJQci3UuxIUp1O8LE7bQDRm85jjXNMPIjdrqz75evHvtQQcbk/sHqtVGxHrt2uQKSmICdmHXUGse2+xhw0Z1CRbk2kgYbRs6Vl6Vk2o3dGP1E3sUKSF0Hx8tgT2ulxP13i1Lm6HugFmpXcQ1sQA2naMzk1478J9QScMIAzpzzIIG0rGOmOEVOX0vlRsr8aFh4XLrI4dlGyiPuZIq09mQT0ktASJglwQFE9JAQ1P8Bsl3vdYBTuaDn+3eAl6F5oxm+3pu4u38BJ8Z4zbdUY2jqzSFPQbr6LcWes+TLFxYcGtSU02z+FZRLNTEJkCuHiVa8Lkf4RYgQ/+vcApdtgFWFQ8NAcEibllXUONYcme7C3A8RhKCiowIvezP0/uz894UZwLVnrth+XErpthuqCkuYW4WUCwItUka5NhYt9eTgR2/9F1moh7uy24OJaK6PcJnK7tBBB8v7ExPWB1Qmp9hFfUcGoqDDmQ4DlyGrGPdgGOQwh85uhCxWBzGpWNs85myPpMC5nRdwpzAm49O6oFjG+BJmXOus+de16HvaBv3zJtENAr1fC2jD/PMKEU4mM+aH4u1Bg4N5bhfGhQ383FRvOAFCXxQJHuqUrJM2vkUr9hS3EvLNNtYaxup0cPkQ5lUOCEmvYku9Se3of6cqjOvt4azd0wMBRaa5j+tS5WYGX3AceA==
  template:
    metadata:
      name: kubescape-infra
      namespace: security

