apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailserver
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailserver
  template:
    metadata:
      labels:
        app: mailserver
    spec:
      containers:
        - name: mailserver
          image: docker.io/falkordb/saasbuilder-mail:0.3.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 49750
          envFrom:
            - secretRef:
                name: mailserver-env
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /healthz/process/liveness
              port: 49750
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 9
          readinessProbe:
            httpGet:
              path: /healthz/process/readiness
              port: 49750
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 18
          startupProbe:
            httpGet:
              path: /healthz/process/startup
              port: 49750
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 60
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 100Mi
      nodeSelector:
        node_pool: backend
---
apiVersion: v1
kind: Service
metadata:
  name: mailserver
  namespace: api
spec:
  selector:
    app: mailserver
  ports:
    - name: http
      protocol: TCP
      port: 49750
      targetPort: 49750
  type: ClusterIP
