---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grype-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: AgAztmfrjYb/FIFLSLh2rOSIVtelaT5wVkNCFdi58ybFefUHNlTt/5FeK5L7JMOhRzARJgSZTsbh+hHvD3XBWXTu2Rq+NKamgMz/I2C4ZKyvcyOVDVh3I9X6E2mDCtJpSfFgsKZrxPphCg4sM/zlyyipFcW3C+3y+tmY5MUDwayqYZ8DpTb4AJgjNeT3laVVtT8VFMXiia5DKsgaxUqSvu6vni2gdsuORiUgiqx24dgpIKbO0av2yrdtT2jhbGwt7WwuRd3hZmmGBemMU6ZlQOK6GgcUHq7+OgVYP/R7UDpZgBunTzUsOH3QvjRsB6umgb3r8G/5mmXfLNLNZD3k9X74vzOZ/MzirVJ8meNNvFtxPAsuee6xXL9W18PghoeC6nE4AjSBT5BPYGNAZFXIfgSyT+mIjuF0XJdRK9owcr4E08u9HJV30A6xCMTL63Mduy2jnXSBDoF1IcVgfLGVW8jfkpOCwI5M0Dj5QCxYFNHyrbwplJI0iPSecD3LEupdNNgSiRYu9M2D1EoNJFBpeQ9NKXtEMdu8FMlJKtxzlDrdA8dXfmA5qf59ei97JyAUoQamcxTJ7uTivZuQ32rQZR1C3bHg08ElnDSXEZN6ILvNweNovIbHvebFBB0ZxyZtRkuxgbw9tS4h872AKoo+gWh7L8lw4Zj1IAJgEo0J0nw08SvIw71HHYHPYQo13bKf/Hct/aMvA+fgPvGT/NBYfYPOHtZfx/c2EF+l0oQsSg==
  template:
    metadata:
      name: grype-infra
      namespace: security

