---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kubescape-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: AgA+MDlMaltUDSdIGtNAnRkLTJhn3EcGHHayURE36yL+Y+oY86R6ajM/sJ4carLavfQhoulU6u/OPnYfVIEjqsp8l2UwwG7UXX8o76ndlDVUXyCfJXLz4c8u2pQCbXB7VbVnE73Q2g3ea5zJVF0vHUbxgNxEw1d9V7TxOXavSPUq7qTUZpwn+recO03CCKPb5p1OPrltzn202Z/cphUszvFTqupNJrdnKQqrgBKnq/XRrewv82pTCR2v9+KMzSYU4CttUBCZPjPROr8FJYEVVlQwmac5Qxx304LEHhsqc8MjP+PxfTRPGuHTQCg8LH1CWcGjPzobijkZnWyf6t9q66OcCWN/fimLrWVtvbVgtD1pjqgedYKcFKV4iGQ8cxKgU4xUyjUQqJI3LH13VOln6GPmwR6YltAMA9qsVCp851J/BL09tjOGCAsQaWKAmrNc0AHlHC5xRroAWg2uHy+FmYyW5AaG/bAh8ytFf1aTYwGSLU7amzuBmqi0a9oiyPMIX0mnLdDkGW6nEMM95Q+Ptn9NWskdzqWNGHyY3uhw2CSnrd/EXxLa2ZkcGLWv6oy4tax1+Wc8Nv6BWCaMc6FXgpIhnPePqmfR2L12rnok3950/bMjgUc7rnRstzCPaTKNtd9H2mkK5GxzpmTCGw0Apyc9Sl5ow57SXc+X/6/ANxCx874mla+hPDfKrGZ8yDlLPUPf5epoAVw2Mwti5pOsMo4U0qDEBhLgFBC1cmc06w==
  template:
    metadata:
      name: kubescape-infra
      namespace: security

