---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prowler-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: AgBGF0gpykyVlkclcC0N9G8U08fxsE+9znyVlpFQ0XDZj6974Rb/hitb+fKTwqk8svJiKyW65kAwVv9TohfV+MlEGtljWCjMyjSZ1VwndYa9t+uqm5IgG9msvpVUaMaWljrZYzD3ujsoN67pdPGQNr5EUZe5FOUa3e9RLECvJOA/FVi1AzffnAD0OSRNpHLSHieIORDa9rTXB8ORxUSzVRMKdftUYsWDEvDgYM8baZC8wHE8CqU2Yxg8W07mTvKbzFWpUUzmazTufv7d81qwUOZPmc8gkRbCOJAptJr46sgFg3a/rf1xcEn5bsmo1NLsSroYVGYSr/anbNLwFGnuFGCeK8Our5irzl1XfmN/Gh5EphRIdvBWur0QiUEoN3+cQY/Mbwk1VOyrOxfudRGrowHQe22t+f0Ryx232zbUL9nIUY+KH+uU4doPIVxsJ+69hN/o18awaVOcc2AWytRjeWx1A6AFzuMl21ul4XtHtrZkpFLjtlEmvPs21cnwNFKWn+/Z+efjrhqymw/NiDJF2tBq7P3Poc/J1WxvaleceiPfnzgnnxp7tq/aBWFHEgyf/u7vyINK8jn7B4tdjC4Hokq13OSBGF04vAtG+5NXlOlQUEOdmRvputuz9aDAHEdXt9ji5DD0FiOY+mdwPhrJZdRgbFEv1QJKLRR+Ig+mcZJ8hx/mvm/zFVXuLsU5ma2umXtI6m7jw8Csc08oql2KXm8WlVUhFx6gRhs7wJY5nw==
  template:
    metadata:
      name: prowler-infra
      namespace: security

