---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloud-evidence-aws-credentials
  namespace: security
spec:
  encryptedData:
    region: AgBtptgTUmN/7XeHRjEBvqGq+TfOwSLADR2/slUET2yWH6HhkEbWgrx+2lWRUPZrBKGmapB1c4NBn33FMIJdPdGnCvbpRaQKCe7RHVTbHiRl7J4xQzUaELbq05yBaC1ErJZHdFXKuN4gDBoIzRB4ogz/m/42SEXIMLyPwLN81jxPuTJHbAHRhUYkB8N0nFVlMd3UGhaIfolZ4SyTlwX8d4SSb9rfy45FBxIiSqldAh28ypz1bDScp5+Fj5hiax+23xz/qTg9Qm617twxlYxfgmota+jmk0naq5Fm7VZJ0CzClSGMYv1POlxAQQhmAXtNFo5hPdtNSmngvoqnPwBtwQjsgamjfC1nHzmjA1on9ihn8Epd0MdvqdgLB8R1mI+beAXlCHXlJ4Y7L+2XdWAlMLw9p7LZgsfMOhz2Hm2cgJQRGbrDIpr4qIkECO2UEjh7HAdNPveUVuhOF4A8oyhxMx36TN9GSvSq45oU7DRaipvfGyp48cIlWD+X17ODF4PLHY+iyiXdQ2TlQQcy+qgdoHl7h+am36QAL+awb71cYloxGp9zu+Hvt5eWhSR6HaaGnwjMvKAwZ35RBpqu7Sr6vig7u2p2YrYPW7IczBRSMG6PPoZ0ksQ4zWg5oCwFzmLMVRPiNzBpZ22aTx3rN8wsrm/p+7R6FHvYNtms5coR2Ah9jbDpcgKotlr9AA+azXelauEgdrBCIJ8YsQiA
    role-arn: AgAH9MZLB/LxWPo6HOf1/soPpvieus6KS6XdvbULRg//G2tlAa6uAySiLtnjR4tAYVp/sszdekffYISfB+wRtqrfgiKPgHfSHuTZK+6H2Ene4u+2O5Poe0FakUIfR19kRUiOYi7cwVzZIdXZCiA36Lq2BGOkoJW977tqAMfzfandLSwiWezTvhtfq9vsRU27AeQJDFkGp+twLSlFKV00U0UM+WkUJ9SbWLriAMewCkmbtjigVbxrIaKZw9cmauLU5rHGZirt3K+LXJqYhHZd4Yw4W1pLh3LMqFlb5+YKraYJLtqBcAaePd0aSp63PWV5DFHmayQsdWsP0Z3dR8l/EGwue7mmf5NtLq3AQGyk4Iu4Y+Pta0TL2hxDm+I7ZoeMRiRniT+SW4b+QrjFzCB5slhYyd5teEWvSeqhFBbhA/txoI2Zz0FzQbn1WhTQx5L4aBIm6tr/X4ic3+HmJPtVzvXF7uFZlk+bMIJrO7QSu3NrGcUykLVaAbpjs09CwTZlMameaAlIP354ns9LJ2oq3OWH4VZ/Vk2RcVZeiAIWaGb8uaMFrUB2/r8TB+qkt9jMWPRmxXw4/8lc6c8OtFAHkCXjoyZhoTpsXEg7LcK+QioEDn2vPzw1OiY4SmrTAh7yGjSWeaUzXFddwcmnWIcW6srQ0fLxMegwfG4rHDLMzeQJ+2hE0n3d1AXh/KukUKK/pVUFtII0KtPCSFnk
  template:
    metadata:
      name: cloud-evidence-aws-credentials
      namespace: security

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloud-evidence-gcs-credentials
  namespace: security
spec:
  encryptedData:
    sa-key.json: AgAw7lzMgtXBrsCJIBfppHUntcF/aAygWchKe73Xgp6uJnUHXDLbF73jmz7mza41IWzHqynO9KChdPJ4FG8//SlqxWTQCp72z7ntouZ94KysgEV/FhrTkUEpD8nqVU8HUjo5VZI6hDdU2O6o/hxkAsHMTT4dmXo5q2qvrrj7KLdQQQpuzUDk7o4Gz/Uivt0vWKF0iAQCnh7pOH/9op2Jn0d842ZJVi0MJoVw+5nC17NXlelm5k4agwp02ipaHO/9NLyP2yyAVpFwqWuo7xFapLE9fPxpCWiJ3V4fNlOLnan+wK4Axnwn4i27gOzOhB7YIS8V3YXRgDdl3CqmGvaHVtQ0a856mRLaeKStV7zTKE808KK2ICcUl94Aedn/tsZHAwaoEtuTAdUfFZbvts+k0uyWwSHk78XuF5aFq2aoV/0J1bFTT6cCTlAt4nVPztWrXA9M277HTu8hoqnOb275JYdTFM2xTHInUaTh4y9UsPIqQS5oHEtJ9Zb9fipDM3WP3OQ/ela5vFSuVzZuuwKx6WcgnGu3bODyLEXex9URUL+r9DFLMHsSscAIArjP7+dIDep2y5o4l4Rs0EDeV0QT4MrfQCwh4zk9aEVviAQ7q7s14PluZIIoe2Y/ayLIV5LkY4NRzz8O/Y97jRINQaJdq53Np0NRjei7Iqe9SG9tnJfVLxA+qYccANEDM62bVHVizaO5+cnLDmf2UFOg
  template:
    metadata:
      name: cloud-evidence-gcs-credentials
      namespace: security

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloud-evidence-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: AgCZwv/LYmtfcB93vo/zu8IFgbiWEFQie+PYBmgEtJfRq7Td30VUwCK2yhIi2jkhHC6NOsH0A0STO6sZbBULshTLVn/Mbx9v8bkn5CNU7Qe21N8Y6lDU9Q0bTvB7NWSVYae8RBEs8a17toPXRaSgUYpsiMIBr/oOIh/SOyPMmiaRaMGFruNQKFVG7+ODBeOt4eG+iZhRYxp3/tVmf7yptG1T7rKrO2bMbgU+hCuqiHuEGS0J8c4pK1l5E7b9vfM2x9SjMYluVeeswIoWMVOiT0r7GRagVHwUb4O1oAXDEIi1P7ODnpu6MgjTsTpnsSu20l2D6F1Cn/9dOChwQjlvnTdloB2VDWwsPQwqkZqIQ5tSDU6yHTvBIC7+pIE7hqWfxJAf/CKB7uaJ/YhfeT0vfCG1cT30ebVXmMcOcgqEGMG56cJXNUZhCllB/HyJugLXAF/PCKxILtXXJC1+mPIunZ3IfW6uQJEJ8i/uQK31cjnYxlrfjYdhH2CNfu1DAC1l3xdNRjH8cGYBwZMizHthFi/Q0DKEuYIvC4woUfBYaUYiE3U3stJwRvaXuntgLLVohswPkIAaEOVsDDj6mQ5HEw/4V1KwWAeBJacdMEj0xYLIm5QF1Pphyyo1clkWmuhnF33Gb3vSw+1blkV+wVuzC62a6u29M+L9VxmVYaKs4dC+ThEgR5R2tDUJMjn21SQ62AR71TgSX6kvWJ3A
  template:
    metadata:
      name: cloud-evidence-infra
      namespace: security

