---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: trufflehog-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: AgARE89eIEFSJ3A5iPLFRcyHAb1B62Jo2KThHWzZvmcnvJ2Lq3oxde+S2Yx2NWcjX7Ss7sqXWsU8SNuBcV3rhKyDN4ELZrA8sJGP6AfVftd6Kk3ZNBfTAqCWX5d2CSKo2aqMNou6Crad09pEuT80SeDWkHrTmIyHMK7xeUK+8h4xks2z0DZS4QuAnMs6i/8O8CjghbrEQ2Xq2hcVnKOHUCGywro94S+LDnYEw4HhazI6Da971K3n+cAOy5r8VvuaNoGF1W9Qw00L9usudp5V5r4/z+xE+Wqqglvs7Penw0N4vQYpPS1WspD4jmDl/NlxClfLUh5YD7ovNjK3kSThSTmR4l8hHJFc1lqeK3bEdGcf0mP1GH5YGplZvHFtru0IdhjEyd9V8VfAnq7AkX5ACHln0vlsyFM3/f+UIWW+eT1KdeIaWPU3ROJE/2AAB5vABxnNXFEhwRDPmNMIoGN2gr/xNhfoQ0S6/Av3iqoSOlajboReNYcQZcOB2hdTiNSVLnOuMJ3vMIQ3VLwtGyB5sQKnoEc1cwgpXvdVldg44dESskyTfwoeLdaRoaVGkrZAP7OXF2ahGuRilcsA/zQK6PsMjmS/F7c76yKTf+sJ5xei0PFpdkHN93iveF72W+4UM6IGitfP5McN95ChTk1gqCA7DVy490YZUfSNLMktPWLaGlq54VoxEIBG4b9xTk66RZ2cTrfSNPeda3+f6Zpsw4zN8hde3m74rRKpdbdumw==
  template:
    metadata:
      name: trufflehog-infra
      namespace: security

