---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kube-bench-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: AgBdOvfRzTcb/XOnqHYPQ1Eku/TNAQzvAVdDsCSsLEV6GLk8QW/CNu0tioMFzcIJzgffDshIYOaxauUZnyFWwC7CNvNXy5B79wfSglVDRw+oYRunmbftEy/C3a6JL41TDp/UGeWz/mDWLgh9auAeFVuKPmc+I1Jj2dRGzXo4ex+llkXWKVGzv4NIZgUu1OOVeoYWr5fBmXm4EvSWS1wovTNYURRutzWtOKqy7/4U0mc+Cf7MGHUnd1Fh9a6XOBIxKieuAkewSaVfh2o8JAIFEhpj1AevqaIfVNmpUmrywyeniXZhL3LYfgAefH/XEon0OUVizTy4IhSIFWHRA+bq3U5xbN2COgDjCX+cCVhbj1xVOne748/I9CL9G0uXXi+fGqq9trLGjC3B2ZHJMMUp0aFV8Le4APNFFBmBSdGL+mjZJEpYpfZE+fLKYDfmbn2j9V0+mbcw40eUIcsiXvpfiDk7m2+cnXJpNRHChLMJJA0+XufDqZTRLoiynLfMktjEBhLpBQ6oDc2yIpHpaOG88DTpeDIoE98jTdA2hhu/tud7aFs94I2tKkdRMaf7R7lF/6GnjZVDItxxse3ukgm13iUbRzSNk7i61Dv6Qu1JKLviVOhQ+Gxcfa1mGg2DzwYFUxoehAlM82ktj/P4tJAiXCDWmrsMqwLq1rATXNTzslWZPrflQ7d3iV0WXv1+aj5Elz/NZ9SyXOoF75TBHMtbFbjFrMkvHuYogetkufEXOA==
  template:
    metadata:
      name: kube-bench-infra
      namespace: security

