apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - wazuh-custom-decoders.yaml
  - wazuh-custom-rules.yaml
  - wazuh-accepted-cves.yaml
  - wazuh-dashboard-soc2.yaml
  - wazuh-dashboard-import-job.yaml
  - wazuh-google-chat-integration.yaml
  - wazuh-alert-exceptions.yaml
  - wazuh-filebeat-finish.yaml