apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ../../base
  - secrets-env-secret.yaml
configMapGenerator:
  - name: kubescape-config
    behavior: create
    literals:
      - cluster-name=app-plane-azure-prod
      - wazuh-syslog-host=136.114.5.250
generatorOptions:
  disableNameSuffixHash: true
patches:
  - path: azure-credentials-patch.yaml
