---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-cluster-key
  namespace: security
spec:
  encryptedData:
    key: AgB81DzkMOEOuBcE6oz92qJnyRqn3uVy1GSf2Py7z3ks1Wu3G6EyGCcbwOzzyJqTq7S2KfELT24GQDZdpQjzZX/ZFOEVqoHxIBv5bMb22tjjvnbYU7atRSLoUqYs9Vsyr/wGTt3LWv/vEyW0/pgO48+c+8SvEcFBwc4PmyktoYxKltX21LaHrABR2Br1g5irmFLb4ZJAhmI0YNmcQwWY0kS2LSV7C34RHXwYev4kVxL2aawfBtNS5nsJeL+KXWu0AW+E76RgXi+XJ9PGz1uu9/PKao6yvPwIiRgCVRPI8MMOPcaYM2Q31GuO3ycQAn1XA6UusWvncT9UlOELmljo56X/clmsfMtezB0fdtAxqD+3W9YmLVVhcmOiNGJn8qcQnzTHrFlyzMkE0n/2aytw/kUwEKbfXM333hvBSjsKvoHPZGjbDL9JhbtwjvaCqkkGv+90alcClQOtL4QWQEV/bplpha8bVWMajXqYWJTzQqTY8YKhNLsnj0kPX7uJkujjLqpJ/dnVNCnMKxCJZKUO4AUK2uXjJf7SwZmAskbxSfuM4uGh+DRP01QZq4SAN0roEj6xhWVYXcl3ht11vW1MzYsHpvP0Qwv5ZnQBsVij1x5D2TeEEKaxWR9iK48eLBKkgSgriV2sn4hzuM31XKZ/WWz6WXlcy+ewPEauTox4fmK+3UYp/PrbjX7ZkdCsQCd+X2tD2xJifhJ6lySKt2NO87DXSWjU/S/PSJKlqGwSOVvlxA==
  template:
    metadata:
      name: wazuh-cluster-key
      namespace: security

