apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ../../base
  - secrets-env-secret.yaml
configMapGenerator:
  - name: kube-bench-config
    behavior: create
    literals:
      - cluster-name=app-plane-gcp-prod
      - wazuh-syslog-host=136.114.5.250
generatorOptions:
  disableNameSuffixHash: true
patches:
  - path: wi-patch.yaml
  - path: remove-nodeselector-patch.yaml
