---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kube-bench-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: AgAwdZkeZAFgo4heQNhltYXwU2iyMtSdjnmboMgYhEP1y4Xqo8paPgN5mLs4CkHt2F38jv4uYOt+uvlck+t+XtGb+avRWs0QN90qfJy7PuZixAiTRaTSmgMY6e9LBUmJ69/p081YJn0U2gkQvg1SYMMiBSrMGEPGKQBBoIJwtwB2ft+b1lOGe0UuUgEydeJPPQCksWwp20+9kruC7OC1Abcxz/hXHQoqiWucPCjocGSVfwZW+jkVfL4aQlfMHnlImyc+M+6IVIImoN6zDW1fJv5c5GbXhPOybHqxq+7+NxH2eX0Y+gjs4xlShNJrwvQCug3z6GTN8NShI9vvCqIoy2OldrMu+9/DG2VqQxOIspV/EyM1DJ8Ac674/hi1vaCxenMQwRqtXhLnAJrmke0PCJPs38N9aYD47+cA+NhWueCyZ9EANDLP0mFNEEzKMlOrkGkUFAii96QHvCIn5cItVHTFLr4FXQY1RUo6HcmGzMqYoVZTkhdqVHLRZFcvFNichpcNDuxnty6tCk1CZAuXTOlgagUJoqx4qD7ZXXJSJtioHfPMlzUF8FSg31ougHYceSejgun/CbK2R9RNWqP4PEBKI7eNhcMNnNGTf5ATpXBwrNz/CA4UJru3+k0NRMh7Tr8BzTo/63duFCvvHHbb6B2lUASpkauV6Uds2Bt0L4PiqMWRWI0vgcsdC/InMEL6h+ioucEClzMVutsbSJmW37Sly4T1ktl0o0ZiIDf53g==
  template:
    metadata:
      name: kube-bench-infra
      namespace: security

