---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-google-chat-webhook
  namespace: security
spec:
  encryptedData:
    WAZUH_GOOGLE_CHAT_WEBHOOK_URL: AgBCxOfdrQuGGmOhYZ2DZ81j+wGp99QZtE5y8Sr9vvFtzz1C9AeVMFaIFMzxWlLnLcpQIzzmZ5HF/uQejq7Wpu2MJKxVx1AiA2+wHsGI9KIK6iu8g612JMnHrZilBBTTBwmoq4CsoNS8L5dJDVRluitOF2+hJ4/u+ZVSBnVyTS44FCCSbEUQBK555XB2SD0IQTwVG6WzqbXPhUeYHsexSoKyh0sWHf0eaj0BJ3lsQIcfHRUEMIJWCtF9uqW2AYisyftkpbPTozfCBpuibGrWPHi98npk5ZB+cfKFmiNzxKE2PmF7pix4U9+5VOeyJiN/sQGvVdIt4KymiFK7Y/OyoPMA1akrwAbMdzn+F7M96+IMNYewy/vuGdscmDMYQ0FWSVqLTKX1RNpD8hn9dYoWtV4USGOMZx5NploM1n5Pr1ykC9x/cfYoJSfDZ88ojERwF7j/yv/6knPJbmoYyEn5dPYNUiYE/Myn3mEPCSMB/qiVkuzjiTUNo6SH8yhhODYct74w8TN2LWdm10HSluq4MIloEWmSV/fpu193LCuQjD7kDTr4V1VM7W02jJOXxUM4Se6B7Wk/Kobd7CU/JpiV87FodsmDb2A9muMJWiR34TyYezn88bO11jSL5WfzG41pRXJmS+qRQi1913YVS7XDCL7cykHL2Ckk1C1RxuzFWL2fk8wCcliB7wjZYOK45emk4pmKjgdzQgp3ex2twMmYKq38Jm4Rrismn6hBqpKFI0ahbrmu7MkrdpIjwZ9ly+Ro4rBXMGKEHmEGNDBhrHdR1xKhrte9wm7SwfmHua0sfx6NiUwVDDoKGFonA+m+zhq75iJ00yveZazwaWFQcp1tNyFSKp1Mp8Jw8J237e4VQlCtUvfXaxoqTdmgz3c/T740Dj8j7xnDBYvzSg==
  template:
    metadata:
      name: wazuh-google-chat-webhook
      namespace: security
