---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-google-chat-webhook
  namespace: security
spec:
  encryptedData:
    WAZUH_GOOGLE_CHAT_WEBHOOK_URL: AgAzw+x1/IIgN49JaZAYj+iiC6mMSjyazpWNI7GrhVTdxlVLHVeZ3s3Ha8vqGLaaEjXxEfrjo3Rl6zW9YJUt0wGePXpRp1ZGlK2nbhS3W0ATMy/I4zm4JeRrsnzc2w939nn4Hxr6r3iZ1WrCWOiezyyEEUL3oNTokDnvLrcOVuxH9TLszcLNdWwHnnsrLOkd5MfrMqYaKeLiI3ktKWSAkFi05D1BD8b4f91cyGVfS1jZ7CpsniTqp8c7Pgxb4vdZccDRfopz2Bj4dEE3pExk6Y5o5fQ7V1VrMOCb12v1mYTaqoQGSvQE5+dIt+L2Szhrqo81y9S3TQqPq+Z7i4G1rJNrFErXDbgiUL+UB+6Jed+l9m+yAScUOsc72S6FK7x3G+8u+aWNowTxXmmTVSxY4SuMzmwnTnopjCkk4MU5moqAts5URoa2DxUZjLYXH3NLELLsDIfqQf+uMx9mvYHgqt4ldWGXlnPHmhvn0lJx277tnD2MJAK3tiMEBEhzNfUnnwJajumDrrkX5/GWMu2z/3ULqjxwY4oJqyMVLe0ZqxgAFyUG8ykuw/6knAGb3MmFVibz+WlKZY1nKNuAzkrkc89XR6nVsyu5hJUBAP8Yg9tqBnfkHtB5A3ojRC51rbX5CPT4CXhxapj6nIlfCfav+8X5VMWbc99oQvfu5bN3aa4FS8Ff4UMhuHmIYJ6/+5EuU9QUmhFHPf44+IAd5RGpwT3WnwOHMb/DOo0mHCuCGuqmAd1fANnAZhgJq624FyV5Z3h4Gtu9GDaF2qsNT3JtDg951X9K0JghmftW0bAE5apzAE/RM7XERvqWyDC8lHeguMeEAh9pzf5OrrgnKT4/FdzC389buWJ1BMPv+rXJmwVENkkdEvr4sCRgg7fcmpX5Wv9FglrGHiCWFw==
  template:
    metadata:
      name: wazuh-google-chat-webhook
      namespace: security

