---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-google-chat-webhook
  namespace: security
spec:
  encryptedData:
    WAZUH_GOOGLE_CHAT_WEBHOOK_URL: AgB4TmGqt7/GSujZSoVR4gAXzwuYPD9x6V6AZ0zbKuEOhzKmHHbT2YcGtyNDlNdYgsMoC93jDovUPRqwp3zHGcPOOPUskd6oU9E+ZiAeS3zqasgR7DXAA5tppN/utfmyuOEa00/tTTgO0YpYGGCyF1AtUYmQAkiUfN4xFczL0Pkj9szDLk65fLnSNlRhmfHRbuoO/VwQ3u1JPZ+YQ/9xgTbko60O15d38lPRE/5HEi66ACeoINg6Yby8gXYL/Yb7l5vQe9W6Ulbepeupyr0cTNJyiRLbshvFz14AljaLxCQq2VKQYMuBMJlV5vJR5iOwMAAvVs6Ydz8H+jK50+WLI/qGpo0kGIAeTZ9qXoCCIngwqjjnkKiSQlMnx1H6TTQdLyOV1bXY/SPLROdkAva414kZIOv4IRBLwXyBrryfVhjmLEyKIx4rttNjhotoYWXrHHHVR2bbyV6LJDVp8dSUpwPHqO6JN90MzQNNZmGKlPvEx9cIv9owixo597iPnEE06rCncNn1Ep8Iaw2W5fgzDrnMmKxNSg4uHoYWuELW1ipprx6pUWkE/rsEFCl7Z+xtn4ydySuwozxJBUSnPRr8brJx/0Zt0L46FJOn+SNADioBYQeSdzGTo/SG1BjIPq1trYVUTGlzMCizC41m8o/zLBzvn4xNySS6bE9uwPeHhIgnx7/zlCJkCAKUEa2lwCsk7j248BSJSP3OrUL8OeMXfM+e3R+F+Q0Re1sh6e/Uhj9VuAOSEseHEaGQj/THhT9GSTVJmcf7GHvL44BXl11xH6sGZBGklZBToX5kPpqoc5kpX7pEMEry8gcJQAjaBtgDGpg1fBJ8SPVsXK7+ry1tPkDoKar4Aersgcdi38mH31+1z/TqHkelBL9fCRsK4JkaEJ7jZvOxESRVIA==
  template:
    metadata:
      name: wazuh-google-chat-webhook
      namespace: security

