apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ../../base
  - secrets-env-secret.yaml
  - aws-credentials-env-secret.yaml
  - azure-credentials-env-secret.yaml
components:
  - ../../components/aws
  - ../../components/azure
configMapGenerator:
  - name: prowler-config
    behavior: create
    literals:
      - cloud-provider=gcp
      - cluster-name=ctrl-plane-dev
      - compliance=cis_2.0_gcp
      - gcp-project-id=ctrl-plane-dev-f7a2434f
      - wazuh-syslog-host=wazuh.security.svc.cluster.local
      - aws-target-name=app-plane-aws-dev
      - azure-target-name=app-plane-azure-dev
generatorOptions:
  disableNameSuffixHash: true
patches:
  - path: wi-patch.yaml
  - path: mutelist-patch.yaml
