---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-indexer-cred
  namespace: observability
spec:
  encryptedData:
    INDEXER_PASSWORD: AgBe5bqIxgtuknHUoFG1BprjPMdU6mRi0jCMZVwLWqbMpYvVAM72g6zaNPIAlxduo5PihjSzzTMegjmgb3IKLPXT2Zxwz+GrLOoe40Y2O00WbVSbWw+fsf1PJYsy1VS01e2fWvJWVuxEUjtTb+RFJYhwo3MdCjy6oSAzpBa5b790lOcSn4lnXwTMWH1HTo2uZt1o6wrWqQdNHP+BFxKvkAEs7Pl89GPYZyYtShdcNniJY5TpL0i1piOElSRTdtihjd5dXDM1GieUWgPW2RI5jtKm4tz6/KW1GZXunhHi8yW9PuBIJt90oj8ZWxeiUXsfIhLGdVEjGFAltrDm0KwyIBMGXUfzvf5O1TF0Q6EYYjZhpGoKYwwddT5VtajWvdl1d2q77Dm/qOAzq5SuZU15cXtKLYqRFw2K7lrqrfCe0Y3OrHMtx75Cn2dJeSYPJqas/oS3SF3AwP9Jcwfky+0HLaCDKdGDDQfZNpanPlEH8P8uNFHw0VZSpd5mGIXwqGtH/NO3Em0PqzCWirv50p7OdHtKhGimSQaGK5oft8ESRDw7BaGkdjJzH3bVPx/7Y4qb9Dj2EeLkvMi9q1RDWwJMnJStB4EUIzv/LJwYal0qmDQbzXKQKfto2afT276OhJh4rcw3wSR0/hJRtpu4kdNzvPpx0+vu7w1k4dXeW041eLA5xHL2ZUAGYdwfc3I/jzTQBETbwk81wbPicFgA0OBij9W30CWnZIELh30TuZ3Khx3+cw==
    INDEXER_USERNAME: AgBBeMNTcG1SSav5ZpftlJF7eikuGT65TQuF1DFDqVwapH7oP7htl2+voOPsleI1HDFkuvkns+J2jQHR70cZE1e/1UNn1Vjj8PLePKpMRa+fivO+E+78cav05coYW+k2i+l/O+v2/nw8PQtUCWSGcc0uKmWwdJNBXCCcYDOGVe/kMHMml2Q9yuEnWbBWgh31QqaB4zZ5uftMaOBL29/sJPkYMowWHHgbEv3b8NSkBkvlq9sBXBCPrn5ppy14aDQfUn+pz2onS3WZ8Q4ujM+gTV+isvGx9oOQ2kpsvc8kyFv509sWqNJuE2Pd26l6rf7u3uUCSvV5F2pFSYXWBpIrHVd3WUOskHN11mbNDLS+jOKUExCwbizuI7/7JgJuJRcC95eL6bvUgRhIoe0OGBrooNIcMkBfgqLThlomjq4St4ngLHzynuFDEhc+Oj+8mrq4q0lKTEs23wnK3Wjmowd0NfqxRHhXDGOkTdrlrd4N23pPlwr2NmAJlo6SyE8PwxVhYda1Rl85hFgoNdpmD+ONwIBxmGRbapUuj/fGf9/mLzHGbMbFn5Hg9pTu6wZnlU79e9QEArcQryabBnpEE51uDevH1OowGM/ty9E03AGUCZCGj+fWID9e/koqfdbpfCDhYJz/ZUBpRe6FbRkb76BaLcIuSPpx0rtHLduIJrIHEjXuilpxBcSGvdaUsfEdq2PXmKj2fARsiA==
  template:
    metadata:
      name: wazuh-indexer-cred
      namespace: observability

