---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grype-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: AgC81oNYuV04sD9bUgWb0stTkxSi+IWW/zIjRh4tvgTPUpJI5pg+21jqj9+4w2ZT5zjCa+A3AEk1DVzFOW/XeWBki5QCkbFWSoMHp2TRB47jz5dUxiGajDrGUHhItt1zk3kzS2Z0jAz/42/p4PLszq4/KX2KPPaHC2O+2OnSuAuHT4Th+4zavFZ+uj+neZHaFpqq30+EnYRRrceXsmCM+kPopkfRkn4yrgfsNa32Up3Vb2ly0/noiWYXM3/LtIHcmctwHhcpW0pvcUhkr7IFhLpvyVWXhrupfvkXcXccNixtJrEJUcfV0rm+RBtVqZgKw+/KJKY7DCd/slEIWiaYTLI+h8FobuDlF4IG9h76ix/aieGikO0btUlKbf+u50R7AWBrdBLskY65HZhhRax3t3sWvZYYd23nSp/F4gLVdpXvCdVb4XU0t1ABJzr9SVLWbx+kJdl/10o37orjs8+ilkhH4iEl5KTmyW+3yMQ7pQ8EK0aVKoB5iTuLw7ZuqmNDWAq8uDRrPiCC7VBovkuBkuuZNcGBtQJzgvP4oWckuhzSZq929Jc2JmvkbTFkRHPpb/rNRj6E/WxqkBLGoqxnnvhR0BLalvdrzJe9SzvP3KZpTpncm0SqSRyWxrGjQCqEHova92KLZtrF8Sd/uMFbneGCL+Dm507eLlf/5CIbUe6zGzIjcJ0+H19auNL3jKiIbQCZucGQVcqrUj6n57qsUN+jutqIeNyMKUZkyVaUhw==
  template:
    metadata:
      name: grype-infra
      namespace: security

