apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentbit
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/FalkorDB/falkordb-dbaas.git
    targetRevision: main
    path: argocd/kustomize/fluentbit/overlays/gke
    kustomize:
      patches:
        - target:
            kind: DaemonSet
            name: fluent-bit
          patch: |-
            apiVersion: apps/v1
            kind: DaemonSet
            metadata:
              name: fluent-bit
            spec:
              template:
                spec:
                  containers:
                    - name: fluent-bit
                      env:
                        - name: CLUSTER_NAME
                          value: ctrl-plane-prod
                        - name: CLOUD_PROVIDER
                          value: gcp
                        - name: CLOUD_REGION
                          value: unknown
  destination:
    server: https://kubernetes.default.svc
    namespace: fluent-bit
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
