---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: omnistrate-api-key
  namespace: observability
spec:
  encryptedData:
    api-key: AgAS59MXHfGZyrZlvkkTnS5rZkhqL9lBpfOmIiD6wrGnyKetaZWlXd8Jdlaj0jQkRx4JOy6/xz+/y552nzEOhKZSJ7kz1E+U0fmsVytrERvpvOKxjcVAr5C3eDINniAqfk7VzWDkLHe0/aUG8Qg4XCN+Gn4FjSfQpDs3gTGTONClgGYLAzQoTcfiYqe14kTLWZ6bUZ/SAzifd6vVZjrvW6MyOfGdRZ2BVmf9zo3VdQK+8LiDOrqo2qEwtKEbLmMBsANcStxk8zFMXZlY4khuDwVOoMRWJ5Wkxbtg61ng9giMewXsExWcctArrV18hO6v1LHtXPJNC4Hh97z3nt7Z24vLKiQ4sAArF5MUy1oyWSJQFf/d1CEGhrupWZZYIJtWYB/ndJAqbzuJw4neFvvqUhDdrFLvHNb9uDaGR8FfjSToZyb6gJKSkRSfmSwPQn6t10o/ZD4I7G7aieuBT6uHtIzajOI9S/E9nJKSgzeVaw2m+VsvM1x9les8a1m4iVx/FUsF0FfwpXtZ8t2EL7VjuW6wjwTtU8RvVRWTb4iHzGVSzZrrtBn6NXjIUfkTZSI/JpCUnMQtLVO9wlLva9Y9bND/253EddSsYnz0f8c5WT7Xj8EzAK2rW9RARHt2x3TJJXC9+afHq72gyleFhU3rKmdqlWDAz6NmTEMGH7pS88iNkUJeHil+waT/6FCYeCVYmnI1U8KxgTQ/XFqXba8iXM4O3ubvC/GlqEAYuwaH1bLxlGgyyqv9IMuZqqeGqblq44pVdBPUsmuAICrttxTO
  template:
    metadata:
      name: omnistrate-api-key
      namespace: observability
