---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: omnistrate-api-key
  namespace: observability
spec:
  encryptedData:
    api-key: AgCtrPym7Q374zNmnqPAxfEWfNnpXgvgxe4C5aCx/olYeJWjQ6e++VzSEP64nN8q9ybwDI4uKbPyKRxj5RlLWmyAlOZuuAv2Ah1NhjQhpsEP8ix+jOdmj7cXVTr1XhvmAXr0Xrb1SQA3oMBZuzY6H7B/0z7DXF6LClbRFdw4x8Ebp4tSGToXsiCnmgOCgYrlsQe5gQqkKxBrAliTT8Ba3f8dp081yYbjIo31WCPUlORWYeA6K84WIIgK8VfggPzzGPP6K8d285IOI/DshMSA+neuhvato9ibdtmamXgqxPr07XQovv/u1hXD8nqB/B+LqlozlbuFNWE1t1iuPIzSPu5EqxmocCeYyeHpHQHNv589CgkJGUiep9gCNAYa4awTnrZ2CPLCqUwRi5sfgdnKYfjwlisAP/YdqY71DonDn/qVteC/AdNJ5FqTv++xz469ChoB7kWs3MMKClHt2xv0zkfH95Fq0bsDIg41eA8d3o2qOYebsJeIP/CUTocnP1sANoBPOeYvP/8ixpwe/j5uVJdL0qN5MSF3Hv9QYP9j0hcwvMNbqKijFOFxUm30ha34VsidPKvR00KdWzy84qBbYX3ZtaB8vSo1SCsXRTUgvq4JJZHmKrhndw77Ttuct7gmJZT7ITlgQJ7h7xe383AXC/YgB37JVkSQKWzbg+OFJNAa9uraLDxoAt4mk3SCwP2KZy6QS0Xz3OHa8IeYOUyequapAhl/zkJBK6Hz5nGxRP+SdTS1LN9lDG1snimSEQZB3j9LiDcvX2YuOHro/wKE
  template:
    metadata:
      name: omnistrate-api-key
      namespace: observability
