---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: omnistrate-api-key
  namespace: observability
spec:
  encryptedData:
    api-key: AgBLrE0gsR5wrbSxsw2KaMdn8niKajHyqKwI3ZKm91v5gmxPm18tLn5XSxA+smMlA0JOTY8Cr896Z4nUgHerTjmAXrQOgyR6m7jruWR0ivsZC6QjpKZhwqcWxp5ttZvqUzHkJZdLV0T1hx6QD+WhX07fITztUQKJipTWspPYGTX96QNy9Vxe2ohFDVAj/HZJq//LrYJ4J2AUTsYVvlwvPaFQe7ZXNRcqyT33uOg4Vn/YyWAwMwKyZrIKoPDMi4eNdNjVs+K9CEClunM84DTkAxKfq6y+hNQAKmjtuc4NU/1sqAszvm3Vtm3q5jxyRgyy/n2Z4WrXffCvnRBLi9UgeCDziqu83KXDLNmad/eHbtrOKiD3GC4nAxLwBLDEjbF+r8NOQ8r8wMNXEaA79KGQETr23UZY/ogWKeDtS3I9nGZ7PXMyVu3+PKsuz4x1TnY7CmOWDKneD7gwO/RhWXYKX9dfDMyyFKEkbq+1uGHlWcGXGaObObqvcQNalhcMgX42zS3K1qmc2PywtK4fd0zhl8B8pUCg8UKM4pizroGGtz53VWTKMlx7IbpsjtJGMslEwM1+07xq3hTqfCzmcXzzxiY0ddGEwQnAUyfdxtqlw/zUqD30cK0NCwgP+s32c07l0ibhhdUhGsd8xLwvJ+JAQ5gWYebB1Y+fpfz4uZqalnsvQfRrUkmh8KaxerSCqgkBGu1k04ajjCngx99cmTzdn/dyWw5KpmngAg6dO6V1m+Wz7/8amD7nrsGJqC60K8YDoneVMW+QBAPhMwy1CVFu
  template:
    metadata:
      name: omnistrate-api-key
      namespace: observability
