apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ../../base
  - secrets-env-secret.yaml
configMapGenerator:
  - name: trufflehog-config
    behavior: create
    literals:
      - cluster-name=ctrl-plane-prod
      - wazuh-syslog-host=wazuh.security.svc.cluster.local
      - "excluded-image-prefixes=docker.io/n8nio/n8n:,docker.io/wazuh/wazuh-manager:,docker.io/wazuh/wazuh-dashboard:,docker.io/nginx/nginx-ingress:,docker.io/bitnamilegacy/kubectl:,ghcr.io/omnistrate/endpoint-monitor-agent:"
generatorOptions:
  disableNameSuffixHash: true
patches:
  - path: wi-patch.yaml
