---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: trufflehog-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: AgAMNWPWO+quNnQqYlaW9gk3go7aqMAzZltdVC1qKDNbUhAQSnd7KCXU/mUGoHjS367s3eR84cvxbQdv5mfTq2zLko2w4HTMCKv8s25YQFNLHxmh0xAxVui65arXMlFIUY6IC9J0s8OJFNtIO0otVaDB+IoaOI1raKq1KQUW4EqUPYCXkE2vf0huBEjVyh3jtzH5HuyeCSfL9ugS+GBq8FipvAHl4HwbA9vTd4vTURzXzuF+0uxi5ny5Z9vd25WIWolNCthJlPldJNG5cd6cisNTF1WnMUYd03Y1PE92zoguq+oWqxbZVsI3GxBek1faa/3NwZfKdTUwBAKIhM0FIZiWFTeyt1DBjgfNwu5zz5GN9anhqxaFX8CAlCjsk0RnLqQEKuMJqh8lesaKGRaDTxdk+H8RN/Q+El8zZDVZW3pFKcmOuIbiUZHEWX1Vz89IdVQGjnSzD55YkwSwdhA8EGuIXuEbNYwzHSGB7LV8DDjSOop+PXLRhCwrvV+egL/E3zwUWL+Euh7A/7lDeEf5zpHsp3fWlPcN61+4xUt9YlEc5N6QCkrKqX4Uhoz7W2aA80oNIqJPjVoE3YuJOT2q0gusHaMqQzKf/Tepgnrq9IEsBG4IRHCNuqKE7SnTvPZ3hQoPuO4EH83nHgTroxzhU5yhEjTEgGAmxEVUZlUfRCJETSeYLfx/QJhWwUoHew438Em80OJjurMran2nhkF9zeCzz/8d4U72m9UDSPDuig==
  template:
    metadata:
      name: trufflehog-infra
      namespace: security

