---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grype-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: AgCJg4/G5bl1FrVvzdty+5V7h9PDf+yWNxcDsJH0weRpy5tSjGW/3K4/SGPf4nnoZmTLgam9dM+qemL1uc8B8kimKZ7ax8jee8ipJ7yRfRX7rmhQZ11fWqlxDfNQGqxbZ5xezuvznXU3TFxuXKkHAjBBrsl5V97Y1slAbwc8+lPFtBLiBJYJu9sCbvpMCXayo4LFSCqPf/juV+puzxbzPcwQUMoUdSXCSGXvVGReA9SfhkfYAQKg3omCpetd8jxn0u79WY88D/KTzXKAwQQN8b3/delHNHxA3gl3aoXlYYfiEQ8mVucLk3zlhyiqapzXrZQc8XQhb5yRb4rE9hASHQt2i+qzYOuYUbymGR7HsscAv27sxMvzh142W53yzV4jdQIdD2tHAj1SG57ed3fjMWzy90jrVNFK1Rl8oib8YwPnu0O5hIjGhuhtEa4nRHunLUU8fIOuc12liw0SIHRxa3V5fLA4Glg/7vPUuYIxWLYnrXSNHSwQ8hPlu7zdsHtrbd12OG0eNV4z+B5R4pzeUm55HSIJJndjJAJUGltPAdi7UttQz+1tPevsPh0wG46ba9O3I5mERV38EvI3dPFF3LTTDOnASXzBfdxXTjz5mCWuL4epVXJ3uPT6bMeUaC0+YIa71NzRm5IuEyF/Z9dKMkb2w8dKOtr1utGY+e1kj6dV34+PTlZ0jKAtDD42fiNN5f7FAXk1RLbPykgLRT9TltTfiLQqKSeMa3yqotaMUw==
  template:
    metadata:
      name: grype-infra
      namespace: security

