---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-agent-key
  namespace: security
spec:
  encryptedData:
    registration-password: AgCqN7KL0pHraR6RQ9ZM2npv3LFlq4Q/kk+tpyYLC/cnJNFl4w6l6tWR0rPfwyYKFhEfeLQhuD7b5EfiCKkwQYnroVgCbQLouHzLa4gWl2cbV3jfza5MvCqvmDXugvyCtwlLw9UZbpdKuvQcdwjjnMVALnWGxMeEt4gSk1byy8Up2SJF7xMa5K/oshoC/y1H6LtlRGV+sbLe8AboeQHydntXCKGW+6YM3r//mKIkYkHaleCypEKmOfVSgYLwVJzqnjv4x5P9I7oAlNduUz4o4W6caMSG2LXgiDFbhhqZc1SMug81EkGa8kr2DNHUaEGwE0Zkfhdw/g6LfoGN8khJTFzflUr+EWrFmTB8wnnaAp+ITq/8SqgZFFs+81ymQA0LOnz2zwl7TRmIw/D5LeOk03Iy0wX1TE3OXG1XgtgIlo4oFgHrCyCoZJ/cXdAV9GcF2R6HP6UZP+sEd63Qkm5gEk+bdYTAxwHSaGi1WIfsOZx9Ish/CILV1/mXVn5L9VSfOXwGOx1lP3Km9QBjkhV9mLjwOCEgQkB0IdQLncek/uerCl68DOtaCYVL/cneJI9xT/IloA7UIefd92DCcrkOsQktnVLmE2ezwxk2/tJTFCw/fKglT+l2cbrvDPveUoq8ZB6uDyCBLF3MpNMFUE/RuvjISPdx5w9pV9amSzlzIkIiCJqrpawdDXZS5QQbK2G/V9/7DxnVAMBAsHDfzDjS+zRBDrP8zuwiHdrtlbLhnJyTwQmLBlDMqKtTsUsCiuC4CRp0Prnt8uNDNyFRStJ8nmNk
    wazuh-manager: AgCYMYFSGN4fjx6pbAxkX2X3+xswIhBIcyuJO1H2vpq7r6FcIjuYP+Yk3qLXE1TE9E20DuIVAYQepL0Ak4ykYJYWpnWwGRE2wy2qS5Y5FJ7ew8ewnHW+e+u+Zf0BquyHo+yI+iIadL6y08k5st8Rt6aCqMPfcTQRBg3mrMoYbJShVt3FFpqkCHCi7IIDajnIIk93rJyi0OreLgduHCenqQ3wSWTShzyISKRwNsmbTnxdk7g9YoyGK/wAnpHqCnEtE9ztDTFwFqkrBJTnR6K3eCLx8QHLgEO+QqXFmdJrN05rhJzEhJ4DNHzNdeYP/aLg7hNEgAGize7+Nyoxc6p6CpLWxZJo54g5iYuJvI/7p6yiWBv2Lqr6KWuLc8tV7OvAov5/fmKXXOpmvI7t91MTzEffxwym3QcXf6wy8hqnCGWSwUtdWk1IACBJTbQmVrveFVr5bRg/bdFd9icqZ5+CzVAxpei0IPai6CpqHVlkdH7g+NyUPUmKKqaXJ0I165pl7RNueL707xBIkacht2GUeucotgPmdF0uszrlpqhvEXB9JGm/oXL+NbE/CaUR4YcoYKNkwDqARrBddbugIJ1Y5FD4x3GQHelSHyo8vHBdTreVq0kPJpYoEr906n6XdDSaJBViLHmiqbn8LKofvYKnzIRxeMF83c7aRobWsw53DbkULi367dc2WXbqoo+kkQsDdhRawZ8PHVre4VZ9MH05
  template:
    metadata:
      name: wazuh-agent-key
      namespace: security

