---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-cluster-key
  namespace: security
spec:
  encryptedData:
    key: AgAFi0ShSBIOqcTC/Myr+m4wkwWONAPhZmACQFrEgHaiMuiomV/3HCIOePhRSLcLCxhR58Nwzb/D5b8BkRADgfTV4ZTVcoWfd4fhURF+aOeQS3tm4IUgjYdKBqJPMMtxqxevb7OnhWIgvcXnOy5/K6fLgNEQzsm1rA8QXKhFn7V8IL/dtBjbvvQUwR5M1AplPDoKAgM9fi7MqTpq/q9ATVGzm3ThS8N7npcS4ejsVFyrEoNf7/sAaagUWxwtmycQoVNLt0X2o5FWUWr4ROMeyG0CIftGhWdug8ehly/hE5UElfWXcSwxD/AIsfbqEHebQnLVWUc1PePTY2A2KNHL8B7rAqyg8jcMmvGbIOdTbo5vaiRysa2Y/5LSd8lpMPYzYA/BSL5Lv3xsHM/XvTURH+rL8INf6AlgqXBerIh7TnSCnUSARWtsKRY4qLuyjiahoS4LSedJHavamvgyORHtrgVvisxLKUanLJniHkf2Lxtzli+5deIc4YbGuxwv2v72bv9KuQKgnIBBYMjX0IChEV8U7/KFvLFaoxdDb8kEUjKTqILnSsRpL2IEYp7yY/oGPnBJmfPwG28yK4VveBw1j3tPclhpN6AQbWQ5OUb7y+r+TlcD//ES08VfcDnk5lAXDyoIqoug7qIpBr2NrKAH+PsftTZM+RlRsLSDnFuNZzaw/vGwaC9IOwcZW5GDZ+iTd5Oacvs6Agkbyjci3O1IKur/z0h6RUeCxxj2jZ3R2aRFug==
  template:
    metadata:
      name: wazuh-cluster-key
      namespace: security

