# SealedSecret: wazuh-cluster-key
# Contains the Wazuh inter-node cluster key.
# Seal with: kubeseal --format yaml --cert certs/ctrl-plane/sealed-secrets/dev/pub-cert.pem
#             --controller-name=sealed-secrets --controller-namespace=kube-system
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-cluster-key
  namespace: security
spec:
  encryptedData:
    key: AgAwM+laOQikICQUczpiy0vfqZqPMtp4GpMztu97daa1cDX38UuMqNcCWvoWFjAhdJL7zcPIfdUJFbkMohbBiXmNk9IH+tMfhHjuYmCJWuDp1TLVDcuJFN7G4H6W4YZl7yFeF31V27djUyeLmDYjjnEDUlnrsuPsGqH/MviE6DUDeMRjxmJ4JtB4NUy7gLQoix2iiVl4XM2hDQJ49fWVYHL3jVwbwp2StMY6/zWjYA53ChFrlubryWd+rcUUTq8aY5PjRuCDcHbUDKXMUN+onEMZ6OVHF6lz3RuPWUnwJ8685dp0APIRn7cp39720rl8Sf6Vgzv0OZPh27P/iAMEW2NjPhuXyd0yZrGQ7B9kX40jWoUiQ+GTBjPPZJOvmke/L/krWrYK37dQaT2k+tCR6xjcARNdkHlJahwPtcWgtq/f5UA3vZDJUoPwV4eYaBgb7CQ1U7s0PZaqq85fzYuM9cfwvGfU//zl84OAJjrhKJs6z7vMvZ12TxwOSu/mqhFku/ZmgTDQzUhX9NvoDrT5E2cn+1matc/H672IjM9A6vZmVi70hrr6RBetXnKa16Ajr5CWNBhWhwdCv7SWIcSHq9+PAfh5UNPLL+OJ9VP63chAedGRZkAqBJN9tzh6QsouvnoT+Mmeo1/6Gz15GKuPtyTqsLmgINNLG5D7jdN9ARLvhuDQnUZg05UrJojBNAP7VYTLE/Br0Q9/lQNZOBNO+rDKHSQUGAhwJbX3KxMYEjdsXA==
  template:
    metadata:
      name: wazuh-cluster-key
      namespace: security
    type: Opaque
