# SealedSecret: wazuh-cluster-key
# Contains the Wazuh inter-node cluster key.
# Seal with: kubeseal --format yaml --cert certs/ctrl-plane/sealed-secrets/dev/pub-cert.pem
#             --controller-name=sealed-secrets --controller-namespace=kube-system
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-cluster-key
  namespace: security
spec:
  encryptedData:
    key: AgBtqkyHZSVvDRBiUhSqbDpz5lnHh1ZHayIMw7WC+CmH46fXo8wtchu1cezj0oazj6MGDQz1XRcGFlXJ2bqQezhem1cRg6WrbpqsQEGPIrjD6T5nLerCSbjq/Ds4WSRNtfc2y9klOqt8jTy404bRe2CrbZKfeF8cVRRV2+C/YeQVSLdh3eZLN/t8hmWm4TvhYIRhPN5D60NSSQ/NDluPMEWs/T6Baw6c25CATd5wuL1Xq1CoDi7lgzNacgQoN9IIVJgImQU7ycGOT8QxNRk6yvWx8h4c3C1YR9z2b3AubxHmKyS3LPmtAdc7WF/DQwyuEjZuey0GexmMJGIbktGf+AIHaMTBg96cvgNhsbUbjmsOF25M568IQ+lMycETsZSduqN6Ow0AP9yEchwJiRRJkWXEqxfmx00yuTev2EJljC5U7FIFbuJnrS4w6/p/zxeT4D1/dtpdFHUtg/hVKAvKMVtD+E798xprbWKaB+mltmlneHmASoqpRROzIYDOuF6NlUbb/4ozVACMS7XMf2Eke90KXPMPv+q1hOZJB3WFdp76xdQQGWd3TF/VSJRP1702muglsvNEBdW6kwfNHCsqYGRDJKc1JKoAJKS10XB04EOIQ0eeyj/FTZevyIrLeqZpdNptRYnUlRHavvFFT8XrA6bMFieQrHmJ72009HUXz7LOn/V9gKE5hO3+AF9fHlnr67femPAcf6kBHMVNi+fLvnAn7kLjMOwWKat250ZFhTGSPQ==
  template:
    metadata:
      name: wazuh-cluster-key
      namespace: security
    type: Opaque
