---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grype-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: AgByxF0Rw77pnpP2Ptl1FrzVVw9saRCS1PSEgrRKl304xVo+pqW2NpuKoosJwdHQoF6W+zDYvvItfxCseoj/PY7ynqVid/AosU/1LkXWZy2WeR90p2lLCxMiUObBRB2UMLRUhfcay+RLPrNMd8rhNDz0BlsCmOMLuqyGkUGGLqMpSEWd7QYVFHSrrb1YpHBVZ8Op4mWft6nTyMfd3UYrL5lDRM6SJiR1l5xxQrhFpZIH176plXoeoS2G/4yBGJvGM9d9azO3DAR4EeNEEifJ+jA+AUN4SLroixg5qPSZUfMJ3dmoHpfxAGgpB0bnQ0VpT9y6ox0iJPn4UlilsDSN0vaKTRx2eV1JlyK6WZOi7ewJBGYQoD6Oipk20mdrUw81sxW6/AfTVzknMs+cV6lxpqWKb2Bmop6yLDxumbq/Z5va8Bz2mg1u+OYCVNrjqS8GdvjqWN72elsBO6gwUs8i6CeZ19GqYl6ajASTOflGrbE5CDrMmyXFVVhauUx54UGt5uMdA+o4QaVbnMMBPVkEmfclnq3B+9fYr1cDZnEaBVjf1RUH5IE1wj/RE/izgXuRwHOLBAEqXsWE9tk8DnBrdksUdCtB5xJNrxCELENlRUyVZNou6SkQVLnIAeZwz4JCNei9XmflphYFCTi9hrgkjhBLUM6M7TT/pyVivRuV3Uv0q/ToWXKfMc2eNvtTzep5POpz4D8Uni0YlamewIW+msrqq+UBatTZm3EQXYJViw==
  template:
    metadata:
      name: grype-infra
      namespace: security

