---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prowler-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: AgAaSCcWqEAEm3qIhUN2vkE9nP7/xoBdESHFIcL7sEeAmMAibeo7oRD2gIj9Z6RhohnLVHingZUFtwUKrunzoto67r639dNt5+eQi2CAwEo2QlnUeD1JHB/B3725fhVJ2sxcs5fA6Q/mn350SXbE4ujW/RsT9yxdAkBY1Bk7k8nVP9erTD3FbnnKN0NumhC+8vb0khSpNInNrZYC2EKTsc5+vrhpvNOLq+KvtNRHNzaL5td25ahhLhphcqJScBeZjPQHMka1MAhT2BOuWcDfVnHIV/RjZJEiVNDRg6eryK9apF9ORCw9b+X+JnklYjFygowtlHiSJ27CM25PXVZa/oqx1Qbc7NZHsC6CM+F4JH5c5qjkQk/xn/AMpXoYLeB17sH0q271RmSU3tn6Bx/3T+XtmRfE2Xv3JiQ0YQlDoGX2xn9oTxFqjSP6HYeltlXC50vsktHyLZ+X/zsGCTJR8gctv96qNTPIHHPddIHN3zyAMEBWTogMoEIV7Fkoky4OoBRwnqDgzB3b9j5uaoJAsbFM49ZrjK4yTDUg6KiCQVWoNHjaLPgJLMm1IC5QO2wtMIJmroVn3PASnNxeKmD7ZxcYtyTR6qzE6HYoOcipGS1d+0x38iv2EpQKo37M+jnRpTpPxIoeWVJLq45mGoXJXGSInXbRjfO/B378nCgq6hqVWYH1HUKcq1YchC5iskOEIMGDg6xKL4w6u2xclzSulnZK6QJdCbJ1iRuKzDColw==
  template:
    metadata:
      name: prowler-infra
      namespace: security

