apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ../../base
# Reuses the wazuh-indexer-cred SealedSecret already provisioned by the
# wazuh-manager overlay in this overlay's destination (ctrl-plane-prod).
patches:
  - path: exporter-config-patch.yaml
