---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloud-evidence-infra
  namespace: security
spec:
  encryptedData:
    evidence-bucket: AgArvD4t4jq++OCW7rLUiJa1KuG/bAhOSV0SOF65j0G5f9X2DDtlT0U3S8pAwwPblqNeHKW4GKttGPz+7n2Bc8vAj9eBxB80olEpNHW+Coixx++EGFbU3IM949Jqp1CrRSYgPCPBuXpbgUiRVcWZwRPz5ETln+Oehpvte6C192hile++o3V7ZSkBDVY8kE9x9SRUpb8xyMMXvsI985fXaWyR87zialMcEQxd5xDaFKvww0waqtq1d3ge4BanaBWi/Ek1PTwHL8osYwmwSonkusXFkrnN55h0Wt4tKdyEDjN6PEcnkSZdEzRMOJ+k3WfLlTjcnzcR/GwmqDN+cDQWP9HuPz8GAC1iS33gUySz2oeSUhp+M2MjmocdMjgwZwQ4DOHvr1FDstSljaCyDtYZElTElBy/hRE75k3i5AHHNfxvjxhjXZ02AHAKoEvEmJlL0Ech6gC1LdcaC3ZevZ3RgU/OF06WRWONqblc5aceBmll+QCXg62p+3dVEfze9Aqdg26DrmEvXn49R2Nrcd2MRYWFsQh7NlUgOgxoHiHqQP+icLtoCWF/GOemUKRt0lGs3eKsboCY5vNENYXtCr0M15v02M62br7dBUot9stKr5ARNtxuOFWkA7+Z1LsXx+yDgpSGfTRHd2ZOH4GNzwJka6SkGMY1v46BVHzV5o9WnFn7MGm9BVX3i4CqYyJkcFWw07MuPxWnn2dT4RmSEqAHySk56/FxEWXyl3GE52/SmQ==
  template:
    metadata:
      name: cloud-evidence-infra
      namespace: security

