---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-indexer-cred
  namespace: observability
spec:
  encryptedData:
    INDEXER_PASSWORD: AgAcKGek5zk52tCG6sx4emYZ7VLVh2QZ1dXkZZQ7iok9JeC9tN4FRaSva/sZrAYlezspoGF0JssvbkxkvKWd62QZpp8JWrFv8d1uQID9E+MZWIYYV7DQF7g6ZzTB1QE8jXHw2V19R4zeR16LvAynFDlHcEhkVJOcR3n527D6spIxCp9XKpQpiE/4ox1+cyAwICTAvkiopUNLfO7ArrX/WGdNBy/hKOy17Dw6sIqD/79dbBczrsIb+fG0nLzD5m1RW8/Es/lQZasoog5+VMBTzQ3FzRrcPqSIdFDXw5oL8/5HEW/p31/cgM9ncjoO8zBSvjonz9epn0vvBhVlJuZkAI7/zrZyvlx8LKvzxyKRgriWrXpS8NsH0T88sYU1g/C3YGXTLZnJmkShbw/5erU7JtttLobJrT6wuI0ZVjRBgCsaNWaRAjIeOQE2kf7G0ZvENrp3i6OsZzb/ds629SJxZnYQjtmTmsIJFjbqvxVs/iSbL4PiJqsaMyzGwekUBWYBLlKYVMtKNqfBsEewbMFsgFTE6effM7dzm8CrxrXYEpfqFO6gzZmpTBrGANiA9odHWQ8l6A5e9XxEqZQk5jfg2o4MRflmaHce7mDj+W7qE3ltbcagK3RHCWUF5Kng+Cxe6VK/F2GAG/vsyBBvYjH2uy7Psn3RX2Z+61dObEhd78rTYGIeNBmOYgtU5MaXKd8C4Z6eiR4t0BNlEZeYROBtjC5XIvaojR9svs1BkEjBhf2q7Q==
    INDEXER_USERNAME: AgBrPgxlp+4Q35Pnyek4SHznbo+iN3WBrAJ1QGvtmCf67tfYBl9J/fR2cDCN0K8PJzmVuXJYorEJLZRfpp3gapIsWk8cxbLwPpISvNxldk8DB47I8Sx1++rZjDvLKhGSv/mLXzmhdbOJOULbRWrjYJl8NXQi3j3YTCGlM6LEIH/BhUFdkOssc6HyyJP3impJIvs5TPyKXKeIOvnxxSzyWJ8l70tSPbjfdSXnqc56lmpDNa70Ye4m0RfYR0PAGy2C9YzVUUNFqGzSIMEzHgIBVvGPhSugit3GzmBmFNfdETMeBcFPbqe2yR/geyqyCTLlsuFM1FUdrmHdvvuqWjCKl9AtwMeDSvycv/bH+EdAcDEJMpilcKAQjHd+qWTJ2x7VqBmBLy0xoVysjvuX0mxOp0TLNEOxtK4zi+H7CuIgJvP8VltWGdgZke9Rnag53sPF0Z8vgriIY9BgD0DUpJuzL5KbTkKiodXZZzhzYm9wKMGeBdowdN5ssXttKies7TvFs581PPLx1eecxOoAXB7autkOCobA//jkQv8DADtVmEmAz1Trg019+qsV/p3Ksf2BIaETid6HPZAY7jGKnD1ixCBkStN3EbExCvnlOg2IFU8sZUmv+EEdulMdkKWcNRILNRmQEljxZqlDy90Uiha4S2BehDzgcxU/K3rTROh728cEVvWHeek/tdq4t+NXmR06BXcRWWeqqQ==
  template:
    metadata:
      name: wazuh-indexer-cred
      namespace: observability

