---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: omnistrate-api-key
  namespace: observability
spec:
  encryptedData:
    api-key: AgDTcNrpObgV1wN4RPl+BGG5LOhPw3ne92dsM6Gx3wkcytIVhUdLqCOKzT5kbW1T3ZVP/nAV8JlY3K683UC9Ijn3iIeEd5RTMH6DVpji5RZisbHCJLjFQBMsbGG6jJeHJbEnMkrzgTLjKeeRMKCYa8X4abZ22sXM5QY271OKch6j1fudMyeMFXbZk26ET0wGkLL8zTBr9zygzQGWLybEWOvlp9OSmPwyJwow9EOnoegWxOEz8KFjXvcfLhXD6SFM+qBZsNc6tsYrFdHq2hquv2DfPdYAqufF3GoYbr5pR3D4wD8cExF98SVx3GEvYrBefCVMBeyfN7WonsB1+5AjkdOIIM7TDUirE8433NU5BND6yNevldrhc2Tc6VQ6xPo1asRSAL51G3S6R5zQrtzFcRXEt31NzTXyOZMdJtbkCOi2UHAm3ahtxmnpMy29zJuwyBl3kTYVoQCrmkt7wa5THWsetJbCt+GeoenluP0md1+SRwGOS2tt0Key4WgAHSqufEW5t4Ue8tHu1XgfqYf2O5dWW9AqBCA2HVwRAvp5g823FkNRYLGSATxqMY7EaGJmXniNvdZOvQWgKZUUH7MIIN8LdyyUQGnG4xDwe0obzjuOUKwBTqgJSj9uBi7da710fQz777rbWNoER8+iQa7Jym7uatwPpH2OgTDSo0M+PY0Wy8bxXNtytN9vcxN4VRJ5n2mL/MG7Q129hn0gLFxW2fjJLGUM+M2SR8X2cWvcxiBRWjv6xCDq8itwP/EgS/R2CO/ubvT6OIDuHegV+Y7B
  template:
    metadata:
      name: omnistrate-api-key
      namespace: observability
