---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: omnistrate-api-key
  namespace: observability
spec:
  encryptedData:
    api-key: AgBDKNdjOSbXzVOAs8ekk/R2+tVluiRGNmetcfcxYjzfi4sovxGD/FhW8bdXOPPaVa5jxvtdf0sThMVo8so2vjZYDRrpQzHHCUxyrokVKmFl5beZGOwZTHiwWkcE/tUnO6ek+//NfT7AW+bp06fJi1UI6MOneiAMA66luMrGd5AqLZvc2/9QMkyOS4xnbFVqEk/jQEu+7HhUc+c4MBkF7NuUl7uD8fcIeiAbgWVZOVsl5rSUoMbyXvywDITbrSaPcqeJ//bVl9pF+Z1AafOBGT0ysm0rk3TLMx7gzhROskvfIxLtvlTaOQgAFXWy6yLIoqnK2MoIQ4TvZibpPZAfnfgFkq91moGi/Uk7XVLnalNnn+rO1W4y9RVHNaL2omVCHXKWtsWKj0ZUAq3NachRJzgMEAXYdM0PG1QDjMF+rb6WdikkqbxKdS2TWCNtU1p1SMMmTOvS7uR6kbZsYCbL6DVMHRu+oRcJnDDADRNCajRrgev+T1fpdLrwYrg0vtt4akZhe0fQqY0c0z9UCeww6mlwwUUrSjcR4LSHTUhQH4FqoHfIyNpOBxzCi04OQFNu/b7h8yXVOO49XIVtW5RH4eH76FzKNoL0DT3dbYSvjSWEPyqCsjgEVW6WAaPN3+oLYzr9DVUGA/mDm2AF/P2CXHThUVNcXZg6HoqCAuGowuDbKewzoP85GkRLg2S8ZBv8PmpyopAk+PJKRXMMOmu8ahXhwua5QBv6MG2s8F0BEth9484oTnJkWeRhIie9U1vVhFKwyLX6pVfd26ihY7rX
  template:
    metadata:
      name: omnistrate-api-key
      namespace: observability
