---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: omnistrate-api-key
  namespace: observability
spec:
  encryptedData:
    api-key: AgAmHOgc0N0S0ZIGxlWP9Kn3+lviwEuN7bR7ttLayY5N5Nn/azlc0HViIPfm1fFnsC4imOPtm5NlbiGgpjuRXPd+MPfVX7PjWZEOYgTdYJE7xgfBmF9W+cbKoohDfBLOCWak0BFpcvsT6/fJotKKMOd2aWWgmz7eyYRDMQ+W9HXz2rdSSWOTgF0PRq6WvgWU2gsG4vSt2CDUWqWh6YJADICMMMsKshi/7Ebl1gYcvk7c+vK2bnlT2YT3pxE8eLh2tbNRMCFnWe/P/nNINgBd8tsAoK+d07+LswnbQ5ijGl1Wrqu7jHt9vBpBHWDWNy3ZdMMMbWF4ayS+YUEOB+Ntzr9lZBdXJEeAjzCyb85pdzydFztfiqjItKAw4cbzNb8qiVUFd1ifsy6xXCXmhqGN/aKmwa/cGZAJwVgLKA+BXRIazEU0uAaPvkxwnUlCW+zsabmrXem9aKzU407PAhDJVN7NvI0gIKHlkxu6BSImxbvpfyQ+QdpiP2sN36161fHKBqJ4fD3cUBX7zFLAKw/qKTz3OGU5TCyZKO+IOXRQBWRBC306d9/Yih3rqE2WImBIy+7aGhJOH+pk3WwRGFv+MBvPRo2xpFtkpwXIifzVpE8L0slqnyeNr0Lqoi8rTO+M9PrnLTK+TaChd3Sp04mCrt4QrMPPXL7LPMwUV+GF0rkRJ8qiLYQRGrT3qTgpAO+Fj5RGH5OWtrJlO2aK8ftL0hf9elz8HtxSU9QET53ExcVCgJMGBnd7w1Q+MmbwtTY+6701iX/FGbrPY+pK9Fkh
  template:
    metadata:
      name: omnistrate-api-key
      namespace: observability
