apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kubescape
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            role: app-plane
        values:
          cloud: '{{ index .metadata.labels "cloud_provider" }}'
  template:
    metadata:
      name: '{{ regexFind "h?c-[A-Za-z0-9]+" .name }}-kubescape'
    spec:
      project: default
      source:
        repoURL: https://github.com/FalkorDB/falkordb-dbaas.git
        targetRevision: main
        path: 'argocd/kustomize/kubescape/overlays/{{ .values.cloud }}-prod'
        kustomize:
          patches:
            - target:
                kind: ConfigMap
                name: kubescape-config
              patch: |-
                - op: replace
                  path: /data/cluster-name
                  value: '{{ regexFind "h?c-[A-Za-z0-9]+" .name }}'
      destination:
        server: "{{.server}}"
        namespace: security
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
